[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"


[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "https://calm-pika-ba89f9.netlify.app/*"
[build]
  functions = "backend/router"

[dev]
  publish = "frontend"