[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "http/*"
  to = "/frontend/index.html"
  status = 200
  to = "/backend/router.js"
[build]
  functions = "backend/router"

[dev]
  publish = "frontend"